### ISSUE TITLE
Cannot unzip data file with provided password

### ISSUE THREAD

**Issue by robmoore** [jan-san/dsci-benchmark#1]
I have found references in the forums to the password for the data.zip. However, I've tried on a  Linux and Mac machine and found I'm unable to decrypt the files with the password I was provided. I'm just curious if there's some particular software you used or something else that might explain the issue.

**Comment by robmoore** [comment]
OK, it seems the password in the forums is actually for a fork of this [repo](https://github.com/hfoffani/dsci-benchmark).

**Comment by jan-san** [comment]
Hi Rob, you're right - this version of the archive was provided for the 3rd iteration of the Capstone project running until April 2015.
I now updated the repo readme to direct visitors to the more recent fork.
